'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServidorServiceReference
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServidorServiceReference.IServidor", CallbackContract:=GetType(ServidorServiceReference.IServidorCallback))>  _
    Public Interface IServidor
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServidor/Transmitir", ReplyAction:="http://tempuri.org/IServidor/TransmitirResponse")>  _
        Sub Transmitir(ByVal mensagem As PowerMessenger.Dominio.Entidades.Mensagem)
        
        <System.ServiceModel.OperationContractAttribute(IsOneWay:=true, Action:="http://tempuri.org/IServidor/Logar")>  _
        Sub Logar(ByVal contato As PowerMessenger.Dominio.Entidades.Contato)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServidor/Deslogar", ReplyAction:="http://tempuri.org/IServidor/DeslogarResponse")>  _
        Sub Deslogar(ByVal contato As PowerMessenger.Dominio.Entidades.Contato)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IServidorCallback
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServidor/Receber", ReplyAction:="http://tempuri.org/IServidor/ReceberResponse")>  _
        Sub Receber(ByVal mensagem As PowerMessenger.Dominio.Entidades.Mensagem)
        
        <System.ServiceModel.OperationContractAttribute(IsOneWay:=true, Action:="http://tempuri.org/IServidor/SelecionarClientesLogados")>  _
        Sub SelecionarClientesLogados(ByVal clientes As System.Collections.Generic.List(Of PowerMessenger.Dominio.Entidades.Contato))
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IServidorChannel
        Inherits ServidorServiceReference.IServidor, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ServidorClient
        Inherits System.ServiceModel.DuplexClientBase(Of ServidorServiceReference.IServidor)
        Implements ServidorServiceReference.IServidor
        
        Public Sub New(ByVal callbackInstance As System.ServiceModel.InstanceContext)
            MyBase.New(callbackInstance)
        End Sub
        
        Public Sub New(ByVal callbackInstance As System.ServiceModel.InstanceContext, ByVal endpointConfigurationName As String)
            MyBase.New(callbackInstance, endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal callbackInstance As System.ServiceModel.InstanceContext, ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(callbackInstance, endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal callbackInstance As System.ServiceModel.InstanceContext, ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(callbackInstance, endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal callbackInstance As System.ServiceModel.InstanceContext, ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(callbackInstance, binding, remoteAddress)
        End Sub
        
        Public Sub Transmitir(ByVal mensagem As PowerMessenger.Dominio.Entidades.Mensagem) Implements ServidorServiceReference.IServidor.Transmitir
            MyBase.Channel.Transmitir(mensagem)
        End Sub
        
        Public Sub Logar(ByVal contato As PowerMessenger.Dominio.Entidades.Contato) Implements ServidorServiceReference.IServidor.Logar
            MyBase.Channel.Logar(contato)
        End Sub
        
        Public Sub Deslogar(ByVal contato As PowerMessenger.Dominio.Entidades.Contato) Implements ServidorServiceReference.IServidor.Deslogar
            MyBase.Channel.Deslogar(contato)
        End Sub
    End Class
End Namespace
